services:
  app:
    build: .
    container_name: php-app-final
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.6
    container_name: mysql-db-final
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      # La ruta correcta al script SQL
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - .env

volumes:
  db-data:
