version: '3.8'

services:
  app:
    build: .
    container_name: php-app-master
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.6
    container_name: mysql-db-master
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - .env

volumes:
  db-data: